apiVersion: gitlab-ce.devops-cli.cfy.cz/v1alpha1
kind: Project
metadata:
  name: fusion
spec:
  description: "Kondor Fusion Risk - OpenShift deployment repository"
  namespace_id: 480
  visibility: private
